In [ ]:
import pandas as pd

def convert_to_three_decimal_places(input_str):
    try:
        # Convert string to float
        float_value = float(input_str)

        # Format float to three significant figures
        #formatted_value = "{:.3g}".format(float_value)

        formatted_value = round(float_value, 3)

        return float(formatted_value)
    except ValueError:
        print("Invalid input. Please enter a valid number.")


memtable_type = ["SkipList", "Vector", "Hash SkipList", "Hash Linklist"]
data_rows = []
for num in range(1,5):
    outfile = "/home/cc/LSMMemoryProfiling/development/rocksdb/examples/__working_branch/outputs/out"+str(num)+".txt"
    f = open(outfile, "r")
    lines = f.readlines()
    counter = 0
    for line in lines:
        if line.startswith("Total time taken"):
            break
        counter+=1
    #print(lines[counter])
    array = []
    array.append(memtable_type[num-1])
    for i in range(counter, counter+7):
        #print(lines[i])
        line = lines[i].split(" ")
        time = line[-2]
        time = convert_to_three_decimal_places(time)
        array.append(time)
    #print(time_array)
    data_rows.append(array)
data_rows
# Define column names
column_names = ['Type', 'Total(s)', 'Time for inserts(s)', 'Time for queries(s)', 'Time for updates(s)', 'Time for deletes(s)', 'Time for range deletes(s)', 'Time for range queries']

# # Create an empty list to store arrays (data rows)
# data_rows = [
#     ['John', 25, 'New York'],
#     ['Alice', 30, 'Los Angeles'],
#     ['Bob', 22, 'Chicago']
# ]

# # Create DataFrame from the list of arrays
df = pd.DataFrame(data_rows, columns=column_names)

# # Display the resulting DataFrame
df